#!/usr/bin/env bash
# ruffy - Autonomous agent loop powered by pi
# Usage: ./ruffy.sh <tasks-yaml> [max_iterations]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---------------------------------------------------------------------------
# Arguments
# ---------------------------------------------------------------------------
if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <tasks-yaml> [max_iterations]"
  echo "  tasks-yaml      Path to the YAML task file generated by the ruffy skill"
  echo "  max_iterations  Number of iterations before pausing for user input (default: 10)"
  exit 1
fi

TASKS_FILE="$1"
MAX_ITERATIONS=10

if [[ $# -ge 2 ]] && [[ "$2" =~ ^[0-9]+$ ]]; then
  MAX_ITERATIONS="$2"
fi

if [[ ! -f "$TASKS_FILE" ]]; then
  echo "Error: Task file not found: $TASKS_FILE"
  exit 1
fi

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
print_divider() {
  echo ""
  echo "==============================================================="
  echo "  $1"
  echo "==============================================================="
}

all_done() {
  # Returns 0 (true) if every story has status: done in the YAML
  # Relies on the agent having written status fields into the file
  python3 - "$TASKS_FILE" <<'EOF'
import sys, yaml
with open(sys.argv[1]) as f:
    data = yaml.safe_load(f)
stories = data.get("userStories", [])
if not stories:
    sys.exit(1)
all_done = all(s.get("status") == "done" for s in stories)
sys.exit(0 if all_done else 1)
EOF
}

run_iteration() {
  local iteration="$1"
  local extra_context="$2"

  print_divider "Ruffy Iteration $iteration of $MAX_ITERATIONS"

  # Build the system prompt, with optional extra context from the user
  PROMPT=$(cat "$SCRIPT_DIR/prompt.md")

  if [[ -n "$extra_context" ]]; then
    PROMPT="$PROMPT

Additional context from user:
$extra_context"
  fi

  # Run pi with the prompt appended to the system prompt.
  # --no-session keeps each iteration independent.
  # No -p so the user sees all in-progress output in real time.
  # Pass the YAML file as the initial user message so the agent has it in context.
  OUTPUT=$(pi --no-session --append-system-prompt "$PROMPT" "@$TASKS_FILE" 2>&1 | tee /dev/stderr) || true

  # Check for completion signal from the agent
  if echo "$OUTPUT" | grep -q "<done>COMPLETE</done>"; then
    return 0  # signal completion
  fi

  return 1
}

# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------
echo "Starting Ruffy"
echo "  Task file:      $TASKS_FILE"
echo "  Max iterations: $MAX_ITERATIONS"

ITERATION=0
EXTRA_CONTEXT=""

while true; do
  ITERATION=$((ITERATION + 1))

  if run_iteration "$ITERATION" "$EXTRA_CONTEXT"; then
    print_divider "All tasks complete!"
    echo "Ruffy finished in $ITERATION iteration(s)."
    exit 0
  fi

  # Clear extra context after first use
  EXTRA_CONTEXT=""

  # Check YAML status as a fallback (in case agent forgot the signal)
  if all_done 2>/dev/null; then
    print_divider "All tasks complete!"
    echo "Ruffy finished in $ITERATION iteration(s)."
    exit 0
  fi

  echo ""
  echo "Iteration $ITERATION complete."

  # Pause at MAX_ITERATIONS and ask the user whether to continue
  if [[ $ITERATION -ge $MAX_ITERATIONS ]]; then
    echo ""
    echo "---------------------------------------------------------------"
    echo "  Ruffy has reached the iteration limit ($MAX_ITERATIONS)."
    echo "  Please review the task file and agent output above."
    echo ""
    echo "  Options:"
    echo "    [enter]     Continue with more iterations"
    echo "    <number>    Set a new iteration limit and continue"
    echo "    q / quit    Stop here"
    echo "---------------------------------------------------------------"
    echo ""
    read -r -p "Your choice (or add context/instructions for the next run): " USER_INPUT

    case "$USER_INPUT" in
      q|quit|exit)
        echo "Stopping. Task file is at: $TASKS_FILE"
        exit 0
        ;;
      ""| *[!0-9]*)
        # Not a plain number — treat as additional context/instructions
        # Reset the counter so we run another MAX_ITERATIONS block
        ITERATION=0
        EXTRA_CONTEXT="$USER_INPUT"
        ;;
      *)
        # Plain number — treat as a new iteration limit
        MAX_ITERATIONS="$USER_INPUT"
        echo "Continuing for up to $MAX_ITERATIONS more iteration(s)..."
        ITERATION=0
        ;;
    esac
  fi

  sleep 1
done
